version: "2"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll:z
      - $PWD/_vendor/bundle:/usr/local/bundle:z
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
